title: Sommer Engineering
author: Drew Sommer
email: drew@sommerengineering.com

url: "https://sommerengineering.com"
linkedin_username: apsommer
github_username: apsommer

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
